var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   o            ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                             xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "       nnn n  n $ nnn              xxxxx                          xvx           ",
   "       n   n n    n  n                                nn                     x  ",
   "  xx   nnn nn   n n  n                               nnnn                    x  ",
   "  x      n n n  n nnn                               nn  nn                   x  ",
   "  x    nnn n  n n n                      xxxxx     nnnnnnnn                o x  ",
   "  x                            o                                             x  ",
   "  x  @       xxxx                                                xx!xx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxfffffxxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x   x                  x     x                    ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx        !!!!      xxxxxxx                    ",
   "                                             !!                                 ",
   "                                            !!!!                                "],
  ["                                    x!!x   nnnnn!                                                             x!x ",
   "                                      x!!x    !!                                                             x!x  ",
   "                                      x!!xxxxxxxxxx                                                          x!x  ",
   "                                      xx!!!!!!!!!!xx         xxxxxxxxxxxxxxxxx                    fff         x!x ",
   "                                       xxxxxxxxxx!!x                 v      vv                   fnnf       o  x!x",
   "                                                xx!nx        x     o                            fnnnf        xx!x ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x    fxfffxf                 n  n n!!!!!!!!!!!!!!xx  ",
   "                                                             xx            nxx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                               x  o  x            xxxxxxx              xxx                        ",
   "                                               x     x                               x x                          ",
   "                                               x     x                                 x                          ",
   "                                               x     x                                xx                          ",
   "                                               xx    x                               x                            ",
   "     $                                         x     x                              x                             ",
   "               xxxxxxxxffffffxxxx              x     x                             x         x                    ",
   "             xxffffffx          x              x     x     xxxxxx    xxxxx   xxxxxxxxx       x                    ",
   "             xxffffffx          x              x    xx               x   x   x               x                    ",
   "     @       xfffffffx          x              x     x               x!!!x   x!!!!!!!!!!!!!!!x                    ",
   "    xxx      xfffffffx          x              x     x               x!!!xfffx!!!xxxxxxxxxxxxx                    ",
   "    x x      xfffffffx         xx              x     x               x!!!!!!!!!!!x                                ",
   "!!!!x x!!!!!!xfffffffxff!!!!ffxx     xx!!!!!!!!xx    x!!!!!!!!!!     x!!!!!!!!!!!x                                ",
   "!!!!x x!!!!!!x       xff!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx                                 ",
   "!!!!x x!!!!!!x       xff!!!!xx                      xx!!!!!!xx !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                !              !                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !n!        !n!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x     o    x       xfx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              xfx                               ",
   "                                      x   x   v v     x                    x!!!x                              ",
   "                                      x   x    v      x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = =      x            xfx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x      = = =x     o      xxx       xfx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                                      x   x           x     x                xxv        xfx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxf fxx xxx          x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx f f xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x          xxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xfx                      ",
   "  xxx                         x     x     x                              o          x!!!x                xxx  ",
   "  x x                         x    xxx    x       xxxx       xxxx                    xxx                 x x  ",
   "  x                           x    xxx    xxxxxx  xnnnn      xnnnn     xxxxx                             x  ",
   "  x                           x           x       xnnnf      xnnnf   x xnfnx x                           x  ",
   "  x                           xx          n       nnnnn      nnnnn   x x|x|x x                           x  ",
   "  x                                       f       vxxxx      xxxxv   xxxxxxxxx                             x  ",
   "  x                xxx                    f                             vxv        xfx                     x  ",
   "  x      $        xnxnx       xx          f             nnnnn           xxx       x!!!x          x         x  ",
   "  x                xxx        x    xxx    n            n     n          x x        xxx          xxx        x  ",
   "  x                xnx        xxxxxxxxxxxxx  xffffx    xffffx    x     xx xx                    xxx        x  ",
   "  x      @         =x         x           x!!x    x!!!!x    x!!!!x   xxx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxx    xxxxxx    xxxxxx    x     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                                                                                                  x x x       ",
   "                                                                                              o   xxx x       ",
   "                                                                                                      x       ",
   "                                                               xxxxfxxxxxfxxxxxfxxxxxfxxxxxfxxxxxfxxxxx       ",
   "                                                              x n x x   x x   x x   x x   x x   x x           ",
   "                                                              xxxvx xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "                                                                x x!!!x x!!!x x!!!x x!!!x x!!!x x!!!!!x       ",
   "                          o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "                         xxx                              xx                                                  ",
   "                          |                                                                                   ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                                                                               fx     fx    o                 ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                  vv     vv      xf                 xf                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x        $x   xxxxxxxxx   xxxxxxxxx   xx                                                xf                  ",
   "  x         x   x       x   x       x   x                                    fxf    xf                        ",
   "  x  @      xxxxx       xxxxx        xxx                                                                      ",
   "  xxxxxxx           xx          xx            xxxxx  fff  xx fff xx fff xxxf                                  ",
   "        x                 = = = = = = = = =   x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
